export enum EventType {
  ORDER_CREATED = 'order.created',
  ORDER_UPDATED = 'order.updated',
  ORDER_STATUS_CHANGED = 'order.status_changed',
  ORDER_CANCELLED = 'order.cancelled',
  CLIENT_DELETED = 'client.deleted',
  PAYMENT_RECEIVED = 'payment.received',
  BOOKING_CONFIRMED = 'booking.confirmed',
  CLIENT_MERGED = 'client.merged',
  AUTH_LOGIN = 'auth.login',
  AUTH_LOGIN_FAILED = 'auth.login_failed',
  AUTH_PASSWORD_CHANGED = 'auth.password_changed',
  AUTH_LOGOUT = 'auth.logout',
  SUPERADMIN_TENANT_ACCESS = 'auth.superadmin_tenant_access',
  SUBSCRIPTION_ACTIVATED = 'subscription.activated',
  SUBSCRIPTION_CHANGED = 'subscription.changed',
  SUBSCRIPTION_CANCELLED = 'subscription.cancelled',
  AUTH_ACCOUNT_LOCKED = 'auth.account_locked',
  AUTH_PASSWORD_RESET_REQUESTED = 'auth.password_reset_requested',
}
