export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  ORDERS: '/orders',
  ORDER_CREATE: '/orders/create',
  ORDER_DETAIL: '/orders/:id',
  CLIENTS: '/clients',
  CLIENT_DETAIL: '/clients/:id',
  VEHICLES: '/vehicles',
  SERVICES: '/services',
  BRANCHES: '/branches',
  BRANCH_DETAIL: '/branches/:id',
  WORK_POSTS: '/work-posts',
  USERS: '/users',
  ROLES: '/roles',
  ROLE_DETAIL: '/roles/:id',
  ANALYTICS: '/analytics',
  AUDIT: '/audit',
  PUBLIC_BOOKING: '/public/:slug',
  SUBSCRIPTION: '/subscription',
  SUBSCRIPTION_PLANS: '/subscription/plans',
  SUBSCRIPTION_BILLING: '/subscription/billing',
  HOW_TO: '/how-to',
  HOW_TO_TOPIC: '/how-to/:topicSlug',
  FORBIDDEN: '/403',
  NOT_FOUND: '/404',
} as const;
